### ISSUE TITLE
Please provide a proper redme

### ISSUE THREAD

**Issue by Shritesh99** [siddharthshah3030/teamAstraNITRR#2]

**Comment by siddharthshah3030** [comment]
@Shritesh99 
## can you provide a proper description of the issue or bug?
As we're unable to understand it from the title of this issue
or is there a silly typo?

feel free to attach files or SS's to make it clear for us to understand and work on it.

**Comment by Shritesh99** [comment]
Please provide a proper redme.md file describing about your project with instructions to run.
